#!/bin/sh

PAK_DIR="$(dirname "$0")"
PAK_NAME="$(basename "$PAK_DIR")"
PAK_NAME="${PAK_NAME%.*}"

export SDCARD_PATH="${SDCARD_PATH:-/mnt/SDCARD}"
export PLATFORM="${PLATFORM:-tg5040}"
export USERDATA_PATH="${USERDATA_PATH:-$SDCARD_PATH/.userdata/$PLATFORM}"
export LOGS_PATH="${LOGS_PATH:-$USERDATA_PATH/logs}"

export VOICE_NOTES_OUTPUT_DIR="${VOICE_NOTES_OUTPUT_DIR:-$SDCARD_PATH/Recordings}"
export VOICE_NOTES_LOG="${VOICE_NOTES_LOG:-$LOGS_PATH/$PAK_NAME.txt}"
export VOICE_NOTES_DEVICE="${VOICE_NOTES_DEVICE:-hw:0,0}"
export VOICE_NOTES_RATE="${VOICE_NOTES_RATE:-48000}"
export VOICE_NOTES_CHANNELS="${VOICE_NOTES_CHANNELS:-1}"
export VOICE_NOTES_FORMAT="${VOICE_NOTES_FORMAT:-S16_LE}"

mkdir -p "$VOICE_NOTES_OUTPUT_DIR" "$LOGS_PATH"

cd "$PAK_DIR" || exit 1
./voice-notes.elf >> "$VOICE_NOTES_LOG" 2>&1
